import Head from 'next/head'
import Link from 'next/link'
import FooterComponent from '../components/footer'

export default function Home() {
  console.log(process.env.NEXT_PUBLIC_HOME_URL)

  return (
    <div className="home--page">
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>{process.env.NEXT_PUBLIC_HOME_URL}</h1>

    <nav className="home--container">
      <Link href="/manage-routes">
        <a className="home--createRoute">
          <p>Minhas rotas</p>
        </a>
      </Link>
      <a className="home--useRoute" href="#footer--contact">
        <p>Contatos</p>
      </a>
    </nav>

    <FooterComponent />
      
    </div>
  )
}

Home.noAuthNeeded = true