import Head from 'next/head'
import Link from 'next/link'
import FooterComponent from '../components/footer'

export default function Home() {

  return (
    <div className="home--page">
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <nav className="home--container">
      <Link href="/create-route">
        <a className="home--createRoute">
          <p>Criar Rota</p>
        </a>
      </Link>
      <Link href="/use-route">
        <a className="home--useRoute">
          <p>Utilizar Rota</p>
        </a>
      </Link>
    </nav>

    <FooterComponent />
      
    </div>
  )
}

Home.noAuthNeeded = true