import Head from 'next/head'
import Link from 'next/link'
import FooterComponent from '../components/footer'
import styles from '../styles/home/style.module.css'

export default function Home() {

  return (
    <div className={styles.page}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <nav className={styles.container}>
      <Link href="/manage-routes">
        <a className={styles.createRoute}>
          <p>Minhas rotas</p>
        </a>
      </Link>
      <a className={styles.useRoute} href="#footer--contact">
        <p>Contatos</p>
      </a>
    </nav>

    <FooterComponent />
      
    </div>
  )
}

Home.noAuthNeeded = true